name: workflow running with parallely

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
  workflow_dispatch:

  jobs:
    job-1:
      runs-on: ubuntu-latest
      steps:
        - run: echo "This is a first job"
        - run: echo "Have one or more steps"
        - run: echo "Which running sequentially"

    job-2:
      runs-on: ubuntu-latest
      steps:
        - run: echo "This is a second job"
    job-3:
      runs-on: ubuntu-latest
      needs:
        - job-1:
        - job-2:
      steps:
        - run: echo "This is 3rd job"

    job-4:
      runs-on: ubuntu-latest
      needs:
        - job-2:
        - job-3:
      steps:
        - run " This is 4th job"

      





      
